--------------------------------------------------------
--  DDL for Index IDXALUMNO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXALUMNO" ON "DBTUTORIA"."ALUMNO" ("A_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXALUMNO_REGULAR
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXALUMNO_REGULAR" ON "DBTUTORIA"."ALUMNO_REGULAR" ("ANIO", "PERIODO", "COD_ALUMNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXAREA_CONOCIMIENTO
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXAREA_CONOCIMIENTO" ON "DBTUTORIA"."AREA_CONOCIMIENTO" ("COD_AREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXASISTENCIA_C_ALUM
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXASISTENCIA_C_ALUM" ON "DBTUTORIA"."ASISTENCIA_C_ALUM" ("FECHA", "A_CODIGO", "GRUPO", "C_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXASISTENCIA_C_PROF
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXASISTENCIA_C_PROF" ON "DBTUTORIA"."ASISTENCIA_C_PROF" ("FECHA", "P_CODIGO", "GRUPO", "C_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXASISTENCIA_T_ALUM
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXASISTENCIA_T_ALUM" ON "DBTUTORIA"."ASISTENCIA_T_ALUM" ("ANIO", "PERIODO", "C_TUTORIA", "SESION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXASISTENCIA_T_PROF
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXASISTENCIA_T_PROF" ON "DBTUTORIA"."ASISTENCIA_T_PROF" ("FECHA_T", "T_ANIO", "T_PERIODO", "T_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXAUDITORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXAUDITORIA" ON "DBTUTORIA"."AUDITORIA" ("ID_ROL", "ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXCICLO
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXCICLO" ON "DBTUTORIA"."CICLO" ("ANIO", "PERIODO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXCICLO_TUTORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXCICLO_TUTORIA" ON "DBTUTORIA"."CICLO_TUTORIA" ("ANIO", "PERIODO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXCURSO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXCURSO" ON "DBTUTORIA"."CURSO" ("C_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXDIAS_CLASE
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXDIAS_CLASE" ON "DBTUTORIA"."DIAS_CLASE" ("ANIO", "PERIODO", "GRUPO", "C_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXDOCENTE_REGULAR
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXDOCENTE_REGULAR" ON "DBTUTORIA"."DOCENTE_REGULAR" ("ANIO", "PERIODO", "COD_DOCENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXGRUPO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXGRUPO" ON "DBTUTORIA"."GRUPO" ("ANIO", "PERIODO", "GRUPO", "C_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXHISTORIAL_NOTAS
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXHISTORIAL_NOTAS" ON "DBTUTORIA"."HISTORIAL_NOTAS" ("ANIO", "PERIODO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXHORA_INI
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXHORA_INI" ON "DBTUTORIA"."HORA_INICIO" ("ID_HORA_INI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXMATRICULA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXMATRICULA" ON "DBTUTORIA"."MATRICULA" ("A_CODIGO", "ANIO", "PERIODO", "GRUPO", "C_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXNOTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXNOTAS" ON "DBTUTORIA"."NOTAS" ("ANIO", "PERIODO", "A_CODIGO", "C_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXOBJETIVOS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXOBJETIVOS" ON "DBTUTORIA"."OBJETIVOS" ("T_ANIO", "T_PERIODO", "T_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXPROFESOR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXPROFESOR" ON "DBTUTORIA"."PROFESOR" ("P_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXPROGRAMACION_TUTORIA
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXPROGRAMACION_TUTORIA" ON "DBTUTORIA"."PROGRAMACION_TUTORIA" ("ANIO", "PERIODO", "C_TUTORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXROL
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXROL" ON "DBTUTORIA"."ROL" ("ID_ROL", "ROL_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXTABLA_DISPONIBILIDAD
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXTABLA_DISPONIBILIDAD" ON "DBTUTORIA"."TABLA_DISPONIBILIDAD" ("ANIO", "PERIODO", "COD_DISP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXTABLA_MAESTRA
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXTABLA_MAESTRA" ON "DBTUTORIA"."TABLA_MAESTRA" ("NOMBRE_TABLA", "NOMBRE_CAMPO", "ID_CAMPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXTABLA_OBSERVACIONES
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXTABLA_OBSERVACIONES" ON "DBTUTORIA"."TABLA_OBSERVACIONES" ("ANIO", "PERIODO", "COD_TUTORIA", "ID_OBSERVACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXTABLA_PREGUNTAS
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXTABLA_PREGUNTAS" ON "DBTUTORIA"."TABLA_PREGUNTAS" ("ID_PREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXTUTORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXTUTORIA" ON "DBTUTORIA"."TUTORIA" ("T_ANIO", "T_PERIODO", "T_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXTUTORIA_ENCUESTA
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXTUTORIA_ENCUESTA" ON "DBTUTORIA"."TUTORIA_ENCUESTA" ("ANIO", "PERIODO", "COD_TUTORIA", "ID_PREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXUSUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXUSUARIO" ON "DBTUTORIA"."USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXUSUARIO_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."IDXUSUARIO_ROL" ON "DBTUTORIA"."USUARIO_ROL" ("ID_ROL", "ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index IDXUSU_ROL_EQUI
--------------------------------------------------------

  CREATE INDEX "DBTUTORIA"."IDXUSU_ROL_EQUI" ON "DBTUTORIA"."USUARIO_ROL_EQUIVALENCIA" ("COD_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX" ;
--------------------------------------------------------
--  DDL for Index PK_ALUMNO_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_ALUMNO_PAR" ON "DBTUTORIA"."ALUMNO_PAR" ("A_CODIGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_ASOC_POSTULACION_TEMA_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_ASOC_POSTULACION_TEMA_PAR" ON "DBTUTORIA"."ASOC_POSTULACION_TEMA_PAR" ("COD_POSTULACION", "CODIGO_TEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_CONVOCATORIA_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_CONVOCATORIA_PAR" ON "DBTUTORIA"."CONVOCATORIA_PAR" ("CODCONVOCATOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_DISPONIBILIDAD_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_DISPONIBILIDAD_PAR" ON "DBTUTORIA"."DISPONIBILIDAD_PAR" ("ID_DISPONIBILIDAD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_HORARIO_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_HORARIO_PAR" ON "DBTUTORIA"."HORARIO_PAR" ("ID_HORARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_MATRICULA_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_MATRICULA_PAR" ON "DBTUTORIA"."MATRICULA_PAR" ("CODMATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_POSTULACION_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_POSTULACION_PAR" ON "DBTUTORIA"."POSTULACION_PAR" ("COD_POSTULACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_PROG_ACADEMICA_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_PROG_ACADEMICA_PAR" ON "DBTUTORIA"."PROG_ACADEMICA_PAR" ("COD_PROGR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_TEMAS_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_TEMAS_PAR" ON "DBTUTORIA"."TEMAS_PAR" ("CODIGO_TEMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_SESION_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_TIPO_SESION_PAR" ON "DBTUTORIA"."TIPO_SESION_PAR" ("COD_TIPSES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index PK_TIPO_TUTORIA_PAR
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."PK_TIPO_TUTORIA_PAR" ON "DBTUTORIA"."TIPO_TUTORIA_PAR" ("CODTUT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index XPKCICLO
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."XPKCICLO" ON "DBTUTORIA"."CICLO" ("ID_CICLO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index XPKHISTORIAL_NOTAS
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."XPKHISTORIAL_NOTAS" ON "DBTUTORIA"."HISTORIAL_NOTAS" ("ANIO", "PERIODO", "PLAN", "COD_CURSO", "COD_ALUMNO", "NOTA_FINAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Index XPKPROGRAMACION_TUTORIA
--------------------------------------------------------

  CREATE UNIQUE INDEX "DBTUTORIA"."XPKPROGRAMACION_TUTORIA" ON "DBTUTORIA"."PROGRAMACION_TUTORIA" ("ANIO", "PERIODO", "C_TUTORIA", "SESION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  Constraints for Table ALUMNO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ALUMNO" ADD CONSTRAINT "XPKALUMNO" PRIMARY KEY ("A_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ALUMNO" MODIFY ("A_CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALUMNO_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ALUMNO_PAR" ADD CONSTRAINT "PK_ALUMNO_PAR" PRIMARY KEY ("A_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ALUMNO_PAR" MODIFY ("A_CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ALUMNO_REGULAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ALUMNO_REGULAR" ADD CONSTRAINT "XPKALUMNO_REGULAR" PRIMARY KEY ("ANIO", "PERIODO", "COD_ALUMNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ALUMNO_REGULAR" MODIFY ("COD_ALUMNO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ALUMNO_REGULAR" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ALUMNO_REGULAR" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AREA_CONOCIMIENTO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."AREA_CONOCIMIENTO" ADD CONSTRAINT "XPKAREA_CONOCIMIENTO" PRIMARY KEY ("COD_AREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."AREA_CONOCIMIENTO" MODIFY ("NOMBRE_AREA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."AREA_CONOCIMIENTO" MODIFY ("COD_AREA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASISTENCIA_C_ALUM
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_ALUM" ADD CONSTRAINT "XPKASISTENCIA_C_ALUM" PRIMARY KEY ("FECHA", "A_CODIGO", "GRUPO", "C_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_ALUM" MODIFY ("C_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_ALUM" MODIFY ("GRUPO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_ALUM" MODIFY ("A_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_ALUM" MODIFY ("FECHA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASISTENCIA_C_PROF
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_PROF" ADD CONSTRAINT "XPKASISTENCIA_C_PROF" PRIMARY KEY ("FECHA", "P_CODIGO", "GRUPO", "C_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_PROF" MODIFY ("C_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_PROF" MODIFY ("GRUPO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_PROF" MODIFY ("P_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_PROF" MODIFY ("FECHA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASISTENCIA_T_ALUM
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_ALUM" ADD CONSTRAINT "XPKASISTENCIA_T_ALUM" PRIMARY KEY ("ANIO", "PERIODO", "C_TUTORIA", "SESION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_ALUM" MODIFY ("ASISTENCIA_T" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_ALUM" MODIFY ("FECHA_TUT" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_ALUM" MODIFY ("SESION" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_ALUM" MODIFY ("C_TUTORIA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_ALUM" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_ALUM" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASISTENCIA_T_PROF
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_PROF" ADD CONSTRAINT "XPKASISTENCIA_T_PROF" PRIMARY KEY ("FECHA_T", "T_ANIO", "T_PERIODO", "T_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_PROF" MODIFY ("T_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_PROF" MODIFY ("T_PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_PROF" MODIFY ("T_ANIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASISTENCIA_T_PROF" MODIFY ("FECHA_T" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASOC_POSTULACION_TEMA_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ASOC_POSTULACION_TEMA_PAR" ADD CONSTRAINT "PK_ASOC_POSTULACION_TEMA_PAR" PRIMARY KEY ("COD_POSTULACION", "CODIGO_TEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ASOC_POSTULACION_TEMA_PAR" MODIFY ("CODIGO_TEMA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ASOC_POSTULACION_TEMA_PAR" MODIFY ("COD_POSTULACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUDITORIA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."AUDITORIA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."AUDITORIA" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CICLO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."CICLO" ADD CONSTRAINT "XPKCICLO" PRIMARY KEY ("ID_CICLO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."CICLO" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."CICLO" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."CICLO" MODIFY ("ID_CICLO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CICLO_TUTORIA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."CICLO_TUTORIA" ADD CONSTRAINT "XPKCICLO_TUTORIA" PRIMARY KEY ("ANIO", "PERIODO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."CICLO_TUTORIA" MODIFY ("FECHA_FIN" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."CICLO_TUTORIA" MODIFY ("FECHA_INI" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."CICLO_TUTORIA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."CICLO_TUTORIA" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONVOCATORIA_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."CONVOCATORIA_PAR" ADD CONSTRAINT "PK_CONVOCATORIA_PAR" PRIMARY KEY ("CODCONVOCATOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."CONVOCATORIA_PAR" MODIFY ("CODCONVOCATOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CURSO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."CURSO" ADD CONSTRAINT "XPKCURSO" PRIMARY KEY ("C_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."CURSO" MODIFY ("CREDITOS" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."CURSO" MODIFY ("C_CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DIAS_CLASE
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."DIAS_CLASE" ADD CONSTRAINT "XPKDIAS_CLASE" PRIMARY KEY ("ANIO", "PERIODO", "GRUPO", "C_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."DIAS_CLASE" MODIFY ("HORA_FIN" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DIAS_CLASE" MODIFY ("HORA_INI" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DIAS_CLASE" MODIFY ("C_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DIAS_CLASE" MODIFY ("GRUPO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DIAS_CLASE" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DIAS_CLASE" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DISPONIBILIDAD_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."DISPONIBILIDAD_PAR" ADD CONSTRAINT "PK_DISPONIBILIDAD_PAR" PRIMARY KEY ("ID_DISPONIBILIDAD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."DISPONIBILIDAD_PAR" MODIFY ("TURNO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DISPONIBILIDAD_PAR" MODIFY ("DIA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DISPONIBILIDAD_PAR" MODIFY ("ID_DISPONIBILIDAD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DOCENTE_REGULAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."DOCENTE_REGULAR" ADD CONSTRAINT "XPKDOCENTE_REGULAR" PRIMARY KEY ("ANIO", "PERIODO", "COD_DOCENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."DOCENTE_REGULAR" MODIFY ("COD_DOCENTE" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DOCENTE_REGULAR" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."DOCENTE_REGULAR" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."GRUPO" ADD CONSTRAINT "XPKGRUPO" PRIMARY KEY ("ANIO", "PERIODO", "GRUPO", "C_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."GRUPO" MODIFY ("C_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."GRUPO" MODIFY ("GRUPO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."GRUPO" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."GRUPO" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORIAL_NOTAS
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."HISTORIAL_NOTAS" ADD CONSTRAINT "XPKHISTORIAL_NOTAS" PRIMARY KEY ("ANIO", "PERIODO", "PLAN", "COD_CURSO", "COD_ALUMNO", "NOTA_FINAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."HISTORIAL_NOTAS" MODIFY ("NOTA_FINAL" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."HISTORIAL_NOTAS" MODIFY ("COD_ALUMNO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."HISTORIAL_NOTAS" MODIFY ("COD_CURSO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."HISTORIAL_NOTAS" MODIFY ("PLAN" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."HISTORIAL_NOTAS" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."HISTORIAL_NOTAS" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HORA_INICIO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."HORA_INICIO" ADD CONSTRAINT "XPKHORA_INI" PRIMARY KEY ("ID_HORA_INI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."HORA_INICIO" MODIFY ("DESC_HORA_INI" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."HORA_INICIO" MODIFY ("ID_HORA_INI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HORARIO_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."HORARIO_PAR" ADD CONSTRAINT "PK_HORARIO_PAR" PRIMARY KEY ("ID_HORARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."HORARIO_PAR" MODIFY ("ID_HORARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATRICULA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."MATRICULA" ADD CONSTRAINT "XPKMATRICULA" PRIMARY KEY ("A_CODIGO", "ANIO", "PERIODO", "GRUPO", "C_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."MATRICULA" MODIFY ("C_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."MATRICULA" MODIFY ("GRUPO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."MATRICULA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."MATRICULA" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."MATRICULA" MODIFY ("A_CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATRICULA_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."MATRICULA_PAR" ADD CONSTRAINT "PK_MATRICULA_PAR" PRIMARY KEY ("CODMATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."MATRICULA_PAR" MODIFY ("CODMATRICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTAS
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."NOTAS" ADD CONSTRAINT "XPKNOTAS" PRIMARY KEY ("ANIO", "PERIODO", "A_CODIGO", "C_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("EF" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("EP" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("E5" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("E4" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("E3" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("E2" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("E1" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("ANIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("C_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."NOTAS" MODIFY ("A_CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OBJETIVOS
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."OBJETIVOS" ADD CONSTRAINT "XPKOBJETIVOS" PRIMARY KEY ("T_ANIO", "T_PERIODO", "T_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."OBJETIVOS" MODIFY ("T_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."OBJETIVOS" MODIFY ("T_PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."OBJETIVOS" MODIFY ("T_ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table POSTULACION_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."POSTULACION_PAR" ADD CONSTRAINT "PK_POSTULACION_PAR" PRIMARY KEY ("COD_POSTULACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."POSTULACION_PAR" MODIFY ("COD_POSTULACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFESOR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."PROFESOR" ADD CONSTRAINT "XPKPROFESOR" PRIMARY KEY ("P_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."PROFESOR" MODIFY ("P_CODIGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROG_ACADEMICA_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."PROG_ACADEMICA_PAR" ADD CONSTRAINT "PK_PROG_ACADEMICA_PAR" PRIMARY KEY ("COD_PROGR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."PROG_ACADEMICA_PAR" MODIFY ("COD_PROGR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROGRAMACION_TUTORIA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."PROGRAMACION_TUTORIA" ADD CONSTRAINT "XPKPROGRAMACION_TUTORIA" PRIMARY KEY ("ANIO", "PERIODO", "C_TUTORIA", "SESION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."PROGRAMACION_TUTORIA" MODIFY ("C_TUTORIA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."PROGRAMACION_TUTORIA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."PROGRAMACION_TUTORIA" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROL
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ROL" ADD CONSTRAINT "XPKROL" PRIMARY KEY ("ID_ROL", "ROL_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."ROL" MODIFY ("DESC_ROL" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ROL" MODIFY ("ROL_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLA_DISPONIBILIDAD
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" ADD CONSTRAINT "XPKTABLA_DISPONIBILIDAD" PRIMARY KEY ("ANIO", "PERIODO", "COD_DISP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("H_FIN" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("H_INICIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("DIA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("COD_CURSO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("COD_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("TIPO_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("COD_DISP" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLA_MAESTRA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TABLA_MAESTRA" ADD CONSTRAINT "XPKTABLA_MAESTRA" PRIMARY KEY ("NOMBRE_TABLA", "NOMBRE_CAMPO", "ID_CAMPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TABLA_MAESTRA" MODIFY ("VALOR_CAMPO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_MAESTRA" MODIFY ("ID_CAMPO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_MAESTRA" MODIFY ("NOMBRE_CAMPO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_MAESTRA" MODIFY ("NOMBRE_TABLA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLA_OBSERVACIONES
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" ADD CONSTRAINT "XPKTABLA_OBSERVACIONES" PRIMARY KEY ("ANIO", "PERIODO", "COD_TUTORIA", "ID_OBSERVACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" MODIFY ("FECHA_REG" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" MODIFY ("SESION_REG" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" MODIFY ("CRITICIDAD" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" MODIFY ("ID_OBSERVACION" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" MODIFY ("COD_TUTORIA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TABLA_PREGUNTAS
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TABLA_PREGUNTAS" ADD CONSTRAINT "XPKTABLA_PREGUNTAS" PRIMARY KEY ("ID_PREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TABLA_PREGUNTAS" MODIFY ("PREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_PREGUNTAS" MODIFY ("TIPO_PREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TABLA_PREGUNTAS" MODIFY ("ID_PREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEMAS_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TEMAS_PAR" ADD CONSTRAINT "PK_TEMAS_PAR" PRIMARY KEY ("CODIGO_TEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TEMAS_PAR" MODIFY ("NOMBRE_TEMA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TEMAS_PAR" MODIFY ("CODIGO_TEMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_SESION_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TIPO_SESION_PAR" ADD CONSTRAINT "PK_TIPO_SESION_PAR" PRIMARY KEY ("COD_TIPSES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TIPO_SESION_PAR" MODIFY ("COD_TIPSES" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_TUTORIA_PAR
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TIPO_TUTORIA_PAR" ADD CONSTRAINT "PK_TIPO_TUTORIA_PAR" PRIMARY KEY ("CODTUT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TIPO_TUTORIA_PAR" MODIFY ("CODTUT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TUTORIA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TUTORIA" ADD CONSTRAINT "XPKTUTORIA" PRIMARY KEY ("T_ANIO", "T_PERIODO", "T_CODIGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("T_TIPO_ALUMNO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("T_DIA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("T_FRECUENCIA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("C_REPITENCIAS" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("C_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("P_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("A_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("T_CODIGO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("T_PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA" MODIFY ("T_ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TUTORIA_ENCUESTA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TUTORIA_ENCUESTA" ADD CONSTRAINT "XPKTUTORIA_ENCUESTA" PRIMARY KEY ("ANIO", "PERIODO", "COD_TUTORIA", "ID_PREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."TUTORIA_ENCUESTA" MODIFY ("FECHA_REGISTRO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA_ENCUESTA" MODIFY ("ID_PREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA_ENCUESTA" MODIFY ("COD_TUTORIA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA_ENCUESTA" MODIFY ("PERIODO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."TUTORIA_ENCUESTA" MODIFY ("ANIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."USUARIO" ADD CONSTRAINT "XPKUSUARIO" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO_ROL
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."USUARIO_ROL" ADD CONSTRAINT "XPKUSUARIO_ROL" PRIMARY KEY ("ID_ROL", "ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."USUARIO_ROL" MODIFY ("ROL" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."USUARIO_ROL" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."USUARIO_ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIO_ROL_EQUIVALENCIA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."USUARIO_ROL_EQUIVALENCIA" ADD CONSTRAINT "XPKUSU_ROL_EQUI" PRIMARY KEY ("COD_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TUTORIAIDX"  ENABLE;
  ALTER TABLE "DBTUTORIA"."USUARIO_ROL_EQUIVALENCIA" MODIFY ("COD_SISTEMA" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."USUARIO_ROL_EQUIVALENCIA" MODIFY ("ROL_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "DBTUTORIA"."USUARIO_ROL_EQUIVALENCIA" MODIFY ("COD_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ASISTENCIA_C_ALUM
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_ALUM" ADD CONSTRAINT "XFKASISTENCIA_C_ALUM" FOREIGN KEY ("A_CODIGO")
	  REFERENCES "DBTUTORIA"."ALUMNO" ("A_CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ASISTENCIA_C_PROF
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."ASISTENCIA_C_PROF" ADD CONSTRAINT "XFKASISTENCIA_C_PROF" FOREIGN KEY ("P_CODIGO")
	  REFERENCES "DBTUTORIA"."PROFESOR" ("P_CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUDITORIA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."AUDITORIA" ADD CONSTRAINT "XFKAUDITORIA" FOREIGN KEY ("ID_ROL", "ID_USUARIO")
	  REFERENCES "DBTUTORIA"."USUARIO_ROL" ("ID_ROL", "ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CURSO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."CURSO" ADD CONSTRAINT "XFKAREA_C" FOREIGN KEY ("AREA_C")
	  REFERENCES "DBTUTORIA"."AREA_CONOCIMIENTO" ("COD_AREA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIAS_CLASE
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."DIAS_CLASE" ADD CONSTRAINT "XFKDIAS_CLASE" FOREIGN KEY ("ANIO", "PERIODO", "GRUPO", "C_CODIGO")
	  REFERENCES "DBTUTORIA"."GRUPO" ("ANIO", "PERIODO", "GRUPO", "C_CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GRUPO
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."GRUPO" ADD CONSTRAINT "XFKGRUPOCURSO" FOREIGN KEY ("C_CODIGO")
	  REFERENCES "DBTUTORIA"."CURSO" ("C_CODIGO") ENABLE;
  ALTER TABLE "DBTUTORIA"."GRUPO" ADD CONSTRAINT "XFKGRUPOPROFESOR" FOREIGN KEY ("P_CODIGO")
	  REFERENCES "DBTUTORIA"."PROFESOR" ("P_CODIGO") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATRICULA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."MATRICULA" ADD CONSTRAINT "XFKMATRICULAALUMNO" FOREIGN KEY ("A_CODIGO")
	  REFERENCES "DBTUTORIA"."ALUMNO" ("A_CODIGO") ENABLE;
  ALTER TABLE "DBTUTORIA"."MATRICULA" ADD CONSTRAINT "XFKMATRICULAGRUPO" FOREIGN KEY ("ANIO", "PERIODO", "GRUPO", "C_CODIGO")
	  REFERENCES "DBTUTORIA"."GRUPO" ("ANIO", "PERIODO", "GRUPO", "C_CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTAS
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."NOTAS" ADD CONSTRAINT "XFKNOTASALUMNO" FOREIGN KEY ("A_CODIGO")
	  REFERENCES "DBTUTORIA"."ALUMNO" ("A_CODIGO") ENABLE;
  ALTER TABLE "DBTUTORIA"."NOTAS" ADD CONSTRAINT "XFKNOTASCURSO" FOREIGN KEY ("C_CODIGO")
	  REFERENCES "DBTUTORIA"."CURSO" ("C_CODIGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TUTORIA
--------------------------------------------------------

  ALTER TABLE "DBTUTORIA"."TUTORIA" ADD CONSTRAINT "XFKTUTORIAALUMNO" FOREIGN KEY ("A_CODIGO")
	  REFERENCES "DBTUTORIA"."ALUMNO" ("A_CODIGO") ON DELETE SET NULL ENABLE;
  ALTER TABLE "DBTUTORIA"."TUTORIA" ADD CONSTRAINT "XFKTUTORIACURSO" FOREIGN KEY ("C_CODIGO")
	  REFERENCES "DBTUTORIA"."CURSO" ("C_CODIGO") ON DELETE SET NULL ENABLE;
  ALTER TABLE "DBTUTORIA"."TUTORIA" ADD CONSTRAINT "XFKTUTORIAPROFESOR" FOREIGN KEY ("P_CODIGO")
	  REFERENCES "DBTUTORIA"."PROFESOR" ("P_CODIGO") ON DELETE SET NULL ENABLE;
