-- ELIMINACIÓN DE DATA CARGADA DE CARGAR NOTAS
DELETE FROM HISTORIAL_NOTAS;

-- ELIMINACIÓN DE DATA CARGADA POR CARGAR DATOS ALUMNOS
DELETE FROM TUTORIA;
DELETE FROM PROGRAMACION_TUTORIA;
DELETE FROM ALUMNO;

-- ELIMINACIÓN DE DATA GENERADA DE REGISTRAR TUTURÍA
DELETE FROM ASISTENCIA_T_ALUM;

COMMIT;
