--------------------------------------------------------
-- Archivo creado  - miércoles-julio-06-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEC_COD_ID_HORARIO
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEC_COD_ID_HORARIO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_COD_MATRICULA
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEC_COD_MATRICULA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_COD_POSTULACION
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEC_COD_POSTULACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_COD_PROGRAM_ACADEMI
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEC_COD_PROGRAM_ACADEMI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_COD_TEMA
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEC_COD_TEMA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_COD_TIPO_SESION
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEC_COD_TIPO_SESION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_COD_TUTORIA
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEC_COD_TUTORIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEC_ID_DISPONIBILIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEC_ID_DISPONIBILIDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_NUMCONV
--------------------------------------------------------

   CREATE SEQUENCE  "DBTUTORIA"."SEQ_NUMCONV"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ALUMNO
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ALUMNO" 
   (	"A_CODIGO" CHAR(8 BYTE), 
	"A_NOMBRE" CHAR(40 BYTE), 
	"A_APELLIDOS" CHAR(40 BYTE), 
	"A_FNACIMIENTO" DATE, 
	"A_DIRECCION" CHAR(40 BYTE), 
	"A_EMAIL" CHAR(40 BYTE), 
	"A_TELEFONO" NUMBER(9,0), 
	"A_DNI" NUMBER(8,0), 
	"A_PLAN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table ALUMNO_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ALUMNO_PAR" 
   (	"A_CODIGO" CHAR(8 BYTE), 
	"ID_USUARIO" VARCHAR2(20 BYTE), 
	"A_NOMBRE" CHAR(40 BYTE), 
	"A_APELLIDOS" CHAR(40 BYTE), 
	"A_FNACIMIENTO" DATE, 
	"A_DIRECCION" CHAR(40 BYTE), 
	"A_EMAIL" CHAR(40 BYTE), 
	"A_TELEFONO" NUMBER(9,0), 
	"A_DNI" NUMBER(8,0), 
	"A_PLAN" NUMBER(38,0), 
	"FLG_TUTOR_PAR" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table ALUMNO_REGULAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ALUMNO_REGULAR" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"COD_ALUMNO" VARCHAR2(10 BYTE), 
	"NOM_ALUMNO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table AREA_CONOCIMIENTO
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."AREA_CONOCIMIENTO" 
   (	"COD_AREA" VARCHAR2(5 BYTE), 
	"NOMBRE_AREA" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table ASISTENCIA_C_ALUM
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ASISTENCIA_C_ALUM" 
   (	"FECHA" DATE, 
	"A_CODIGO" CHAR(8 BYTE), 
	"GRUPO" NUMBER(2,0), 
	"C_CODIGO" CHAR(8 BYTE), 
	"ASISTENCIA" CHAR(1 BYTE), 
	"OBSERVACION" CHAR(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table ASISTENCIA_C_PROF
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ASISTENCIA_C_PROF" 
   (	"FECHA" DATE, 
	"P_CODIGO" CHAR(8 BYTE), 
	"GRUPO" NUMBER(2,0), 
	"C_CODIGO" CHAR(8 BYTE), 
	"ASISTENCIA" CHAR(1 BYTE), 
	"OBSERVACION" CHAR(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table ASISTENCIA_T_ALUM
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ASISTENCIA_T_ALUM" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"C_TUTORIA" VARCHAR2(10 BYTE), 
	"SESION" NUMBER(*,0), 
	"FECHA_TUT" DATE, 
	"ASISTENCIA_T" VARCHAR2(1 BYTE), 
	"JUSTIFICACION" VARCHAR2(20 BYTE), 
	"OBSERVACION_T" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table ASISTENCIA_T_PROF
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ASISTENCIA_T_PROF" 
   (	"FECHA_T" DATE, 
	"ASISTENCIA_T" CHAR(1 BYTE), 
	"OBSERVACION_T" CHAR(250 BYTE), 
	"T_ANIO" NUMBER(4,0), 
	"T_PERIODO" NUMBER(2,0), 
	"T_CODIGO" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table ASOC_POSTULACION_TEMA_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ASOC_POSTULACION_TEMA_PAR" 
   (	"COD_POSTULACION" NUMBER(*,0), 
	"CODIGO_TEMA" NUMBER(*,0), 
	"FLAG_APROBACION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table ASOC_TEMA_CONVOCATORIA_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ASOC_TEMA_CONVOCATORIA_PAR" 
   (	"CODCONVOCATOR" NUMBER(*,0), 
	"CODIGO_TEMA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table AUDITORIA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."AUDITORIA" 
   (	"ID_ROL" NUMBER, 
	"ID_USUARIO" VARCHAR2(50 BYTE), 
	"IP_MAQUINA" VARCHAR2(50 BYTE), 
	"HORA" CHAR(8 BYTE), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table CICLO
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."CICLO" 
   (	"ID_CICLO" NUMBER(*,0), 
	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"ACTIVO" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table CICLO_TUTORIA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."CICLO_TUTORIA" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"FECHA_INI" DATE, 
	"FECHA_FIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table CONVOCATORIA_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."CONVOCATORIA_PAR" 
   (	"CODCONVOCATOR" NUMBER(*,0), 
	"ID_CICLO" NUMBER(38,0), 
	"FEC_INI" DATE, 
	"FEC_FIN" DATE, 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table CURSO
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."CURSO" 
   (	"C_CODIGO" CHAR(8 BYTE), 
	"NOMBRE" CHAR(50 BYTE), 
	"CREDITOS" NUMBER(*,0), 
	"AREA_C" VARCHAR2(5 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table DIAS_CLASE
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."DIAS_CLASE" 
   (	"ANIO" NUMBER(4,0), 
	"PERIODO" NUMBER(2,0), 
	"GRUPO" NUMBER(2,0), 
	"C_CODIGO" CHAR(8 BYTE), 
	"DIA" CHAR(40 BYTE), 
	"HORA_INI" CHAR(8 BYTE), 
	"HORA_FIN" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table DISPONIBILIDAD_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."DISPONIBILIDAD_PAR" 
   (	"ID_DISPONIBILIDAD" NUMBER(*,0), 
	"COD_POSTULACION" NUMBER(*,0), 
	"DIA" VARCHAR2(15 BYTE), 
	"TURNO" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table DOCENTE_REGULAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."DOCENTE_REGULAR" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"COD_DOCENTE" VARCHAR2(10 BYTE), 
	"NOM_DOCENTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table GRUPO
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."GRUPO" 
   (	"ANIO" NUMBER(4,0), 
	"PERIODO" NUMBER(2,0), 
	"GRUPO" NUMBER(2,0), 
	"C_CODIGO" CHAR(8 BYTE), 
	"P_CODIGO" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table HISTORIAL_NOTAS
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."HISTORIAL_NOTAS" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"PLAN" NUMBER(*,0), 
	"COD_CURSO" CHAR(40 BYTE), 
	"COD_ALUMNO" CHAR(40 BYTE), 
	"NOTA_FINAL" NUMBER(*,0), 
	"CREDITOS" NUMBER(*,0), 
	"NOM_ALUMNO" CHAR(50 BYTE), 
	"NOM_DOCENTE" CHAR(50 BYTE), 
	"NOM_CURSO" CHAR(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table HORA_INICIO
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."HORA_INICIO" 
   (	"ID_HORA_INI" VARCHAR2(5 BYTE), 
	"DESC_HORA_INI" CHAR(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table HORARIO_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."HORARIO_PAR" 
   (	"ID_HORARIO" NUMBER(*,0), 
	"COD_PROGR" NUMBER(*,0), 
	"HORA_INI" CHAR(8 BYTE), 
	"HORA_FIN" CHAR(8 BYTE), 
	"DIA_SEMANA" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table MATRICULA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."MATRICULA" 
   (	"A_CODIGO" CHAR(8 BYTE), 
	"REPITENCIAS" NUMBER(*,0), 
	"ANIO" NUMBER(4,0), 
	"PERIODO" NUMBER(2,0), 
	"GRUPO" NUMBER(2,0), 
	"C_CODIGO" CHAR(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table MATRICULA_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."MATRICULA_PAR" 
   (	"CODMATRICULA" NUMBER(*,0), 
	"A_CODIGO" CHAR(8 BYTE), 
	"COD_PROGR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table NOTAS
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."NOTAS" 
   (	"A_CODIGO" CHAR(8 BYTE), 
	"C_CODIGO" CHAR(8 BYTE), 
	"ANIO" NUMBER(4,0), 
	"PERIODO" CHAR(2 BYTE), 
	"E1" FLOAT(63), 
	"E2" FLOAT(63), 
	"E3" FLOAT(63), 
	"E4" FLOAT(63), 
	"E5" FLOAT(63), 
	"EP" FLOAT(63), 
	"EF" FLOAT(63)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table OBJETIVOS
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."OBJETIVOS" 
   (	"T_ANIO" NUMBER(4,0), 
	"T_PERIODO" NUMBER(2,0), 
	"T_CODIGO" CHAR(8 BYTE), 
	"APROBAR_PARIAL" VARCHAR2(1 BYTE), 
	"APROBAR_FINAL" VARCHAR2(1 BYTE), 
	"APROBAR_SUSTI" VARCHAR2(1 BYTE), 
	"APROBAR_CURSO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table POSTULACION_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."POSTULACION_PAR" 
   (	"COD_POSTULACION" NUMBER(*,0), 
	"A_CODIGO" CHAR(8 BYTE), 
	"CODCONVOCATOR" NUMBER(*,0), 
	"CURRICULUM" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" 
 LOB ("CURRICULUM") STORE AS BASICFILE (
  TABLESPACE "TS_TUTORIA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PROFESOR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."PROFESOR" 
   (	"P_CODIGO" CHAR(8 BYTE), 
	"P_NOMBRE" CHAR(25 BYTE), 
	"P_APELLIDOS" CHAR(25 BYTE), 
	"P_FNACIMIENTO" DATE, 
	"P_DIRECCION" CHAR(40 BYTE), 
	"P_EMAIL" CHAR(40 BYTE), 
	"P_TELEFONO" NUMBER(9,0), 
	"P_DNI" NUMBER(8,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table PROG_ACADEMICA_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."PROG_ACADEMICA_PAR" 
   (	"COD_PROGR" NUMBER(*,0), 
	"CODTUT" NUMBER(*,0), 
	"COD_POSTULACION" NUMBER(*,0), 
	"CODIGO_TEMA" NUMBER(*,0), 
	"NUMVACANTES" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(140 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table PROGRAMACION_TUTORIA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."PROGRAMACION_TUTORIA" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"C_TUTORIA" CHAR(8 BYTE), 
	"SESION" NUMBER(*,0), 
	"FECHA_TUT" DATE, 
	"HORA_INI" CHAR(10 BYTE), 
	"HORA_FIN" CHAR(10 BYTE), 
	"ESTADO" VARCHAR2(1 BYTE), 
	"ACTA" BLOB, 
	"NOMBRE_ACTA" VARCHAR2(50 BYTE), 
	"ESTADO_ACTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" 
 LOB ("ACTA") STORE AS BASICFILE (
  TABLESPACE "TS_TUTORIA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ROL
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."ROL" 
   (	"ID_ROL" NUMBER(*,0), 
	"ROL_USUARIO" VARCHAR2(20 BYTE), 
	"DESC_ROL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table SESIONES_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."SESIONES_PAR" 
   (	"COD_TIPSES" NUMBER(*,0), 
	"COD_PROGR" NUMBER(*,0), 
	"NUMSESION" NUMBER(*,0), 
	"FECHA" DATE, 
	"DESCRIPCION" VARCHAR2(140 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TABLA_DISPONIBILIDAD
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TABLA_DISPONIBILIDAD" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"COD_DISP" VARCHAR2(10 BYTE), 
	"TIPO_USUARIO" NUMBER(*,0), 
	"COD_USUARIO" VARCHAR2(10 BYTE), 
	"COD_CURSO" VARCHAR2(8 BYTE), 
	"DIA" VARCHAR2(10 BYTE), 
	"H_INICIO" VARCHAR2(10 BYTE), 
	"H_FIN" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TABLA_MAESTRA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TABLA_MAESTRA" 
   (	"NOMBRE_TABLA" VARCHAR2(20 BYTE), 
	"NOMBRE_CAMPO" VARCHAR2(20 BYTE), 
	"ID_CAMPO" NUMBER(*,0), 
	"VALOR_CAMPO" VARCHAR2(50 BYTE), 
	"ESTADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TABLA_OBSERVACIONES
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TABLA_OBSERVACIONES" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"COD_TUTORIA" CHAR(8 BYTE), 
	"ID_OBSERVACION" NUMBER(*,0), 
	"CRITICIDAD" VARCHAR2(10 BYTE), 
	"SESION_REG" NUMBER(*,0), 
	"FECHA_REG" VARCHAR2(10 BYTE), 
	"SESION_CIERRE" NUMBER(*,0), 
	"OBSERV_CIERRE" VARCHAR2(250 BYTE), 
	"FECHA_CIERRE" VARCHAR2(10 BYTE), 
	"ESTADO_OBSERV" NUMBER(*,0), 
	"FECHA_ENTREGA" VARCHAR2(10 BYTE), 
	"RAZON" VARCHAR2(250 BYTE), 
	"FECHA_CUMPLIMIENTO" VARCHAR2(250 BYTE), 
	"TAREA" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TABLA_PREGUNTAS
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TABLA_PREGUNTAS" 
   (	"ID_PREGUNTA" NUMBER(*,0), 
	"TIPO_PREGUNTA" VARCHAR2(20 BYTE), 
	"PREGUNTA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TEMAS_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TEMAS_PAR" 
   (	"CODIGO_TEMA" NUMBER(*,0), 
	"C_CODIGO" CHAR(8 BYTE), 
	"NOMBRE_TEMA" VARCHAR2(100 BYTE), 
	"DESCRIPCION_TEMA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TIPO_SESION_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TIPO_SESION_PAR" 
   (	"COD_TIPSES" NUMBER(*,0), 
	"TIPO_SESION" CHAR(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TIPO_TUTORIA_PAR
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TIPO_TUTORIA_PAR" 
   (	"CODTUT" NUMBER(*,0), 
	"TIPOTUTORIA" VARCHAR2(10 BYTE), 
	"NUMERO_VACANTES" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TRAZA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TRAZA" 
   (	"OPERACION" VARCHAR2(20 BYTE), 
	"PARAMETRO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TUTORIA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TUTORIA" 
   (	"T_ANIO" NUMBER(4,0), 
	"T_PERIODO" NUMBER(2,0), 
	"T_CODIGO" CHAR(8 BYTE), 
	"A_CODIGO" CHAR(8 BYTE), 
	"P_CODIGO" CHAR(8 BYTE), 
	"C_CODIGO" CHAR(8 BYTE), 
	"C_REPITENCIAS" NUMBER(2,0), 
	"T_FRECUENCIA" NUMBER(1,0), 
	"T_DIA" CHAR(10 BYTE), 
	"T_TIPO_ALUMNO" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table TUTORIA_ENCUESTA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."TUTORIA_ENCUESTA" 
   (	"ANIO" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"COD_TUTORIA" CHAR(8 BYTE), 
	"COD_PSICOLOGA" VARCHAR2(20 BYTE), 
	"ID_PREGUNTA" NUMBER(*,0), 
	"RESPUESTA" VARCHAR2(150 BYTE), 
	"CALIF_TUTOR" VARCHAR2(15 BYTE), 
	"CALIF_PSICO" VARCHAR2(15 BYTE), 
	"FECHA_REGISTRO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."USUARIO" 
   (	"ID_USUARIO" VARCHAR2(20 BYTE), 
	"CLAVE" VARCHAR2(50 BYTE), 
	"NOMBRES" VARCHAR2(64 BYTE), 
	"MATERNO" VARCHAR2(32 BYTE), 
	"PATERNO" VARCHAR2(32 BYTE), 
	"CORREO" VARCHAR2(64 BYTE), 
	"DIRECCION" VARCHAR2(128 BYTE), 
	"TELEFONO" VARCHAR2(32 BYTE), 
	"ESTADO" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table USUARIO_ROL
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."USUARIO_ROL" 
   (	"ID_ROL" NUMBER, 
	"ID_USUARIO" VARCHAR2(50 BYTE), 
	"ROL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
--------------------------------------------------------
--  DDL for Table USUARIO_ROL_EQUIVALENCIA
--------------------------------------------------------

  CREATE TABLE "DBTUTORIA"."USUARIO_ROL_EQUIVALENCIA" 
   (	"COD_USUARIO" VARCHAR2(20 BYTE), 
	"ROL_USUARIO" VARCHAR2(20 BYTE), 
	"COD_SISTEMA" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_TUTORIA" ;
