-- como usuario sys as sysdba
-- creamos el usuario
CREATE USER DBTUTORIA IDENTIFIED BY DBTUTORIA;
-- privilegios
GRANT CONNECT, RESOURCE TO DBTUTORIA;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO DBTUTORIA;
-- tablespace 
CREATE TABLESPACE TS_TUTORIA
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\TS_TUTORIA.ORA' 
SIZE 50 m 
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;

CREATE TABLESPACE TUTORIAIDX
DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\TUTORIAIDX.ORA' 
SIZE 50 m 
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;